name: Pull from AWS ECR

on:
  workflow_call:
    secrets: 
      TAG_VERSION:
        required: true
env:
  AWS_ACCOUNT_NUMBER: 584431362645
jobs:
  Pull_ECR:
    name: Pull Docker image from ECR
    runs-on: ubuntu-latest
    permissions: # These permissions are needed to interact with GitHub's OIDC Token endpoint
      id-token: write
      contents: read 
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT_NUMBER}}:role/github-actions-role
          role-session-name: Session-GitHubActions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: cars-actions
          IMAGE_TAG: ${{ secrets.TAG_VERSION }}
        run: |
          docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG