# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Python CI to AWS ECR

on:
  push:
    branches: [ main ]
    # paths:
    #   - "cars/*" # only trigger workflow for code changes here 
  pull_request:
    branches: [ main ]
env:
  AWS_ACCOUNT_NUMBER: 584431362645
permissions:
  contents: read
jobs:
  build-python:
    runs-on: ubuntu-latest
    permissions: # These permissions are needed to interact with GitHub's OIDC Token endpoint
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT_NUMBER}}:role/github-actions-role
        role-session-name: Session-GitHubActions

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: cars-action
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
       
