name: Python CI to AWS ECR

on:
  push:
    branches: [ main ]
    # paths:
    #   - "cars/*" # only trigger workflow for code changes here 
  pull_request:
    branches: [ main ]
env:
  AWS_ACCOUNT_NUMBER: 584431362645
permissions:
  contents: read
jobs:
  build-python:
    runs-on: ubuntu-latest
    permissions: # These permissions are needed to interact with GitHub's OIDC Token endpoint
      id-token: write
      contents: read
    outputs:
      tag-version: ${{ steps.build-tag-push-ecr.outputs.env.IMAGE_TAG }}
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT_NUMBER}}:role/github-actions-role
        role-session-name: Session-GitHubActions

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      id: build-tag-push-ecr
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: cars-actions
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  pull-python:
    runs-on: ubuntu-latest
    needs: build-python
    steps:
    - name: Use tag version from build-python job
      run: echo "The tag version is ${{ needs.build-python.outputs.tag-version }}"
      env:
        TAG_VERSION: ${{ needs.build-python.outputs.tag-version }}
    - name: Pull from ECR
      uses: ./.github/workflows/cd.yaml
      with:
        tag-version: ${{ needs.build-python.outputs.tag-version }}        
